import json
import os  # For path handling, like checking if a file exists


def load_blueprint(filepath="blueprint.json"):
    """
    Loads and parses the JSON blueprint file.
    Args:
        filepath (str): The path to the JSON blueprint file.
    Returns:
        dict: The parsed blueprint data as a dictionary, or None if an error occurs.
    """
    if not os.path.exists(filepath):
        print(f"Error: Blueprint file not found at '{filepath}'")
        return None
    try:
        with open(filepath, "r") as f:
            blueprint_data = json.load(f)
        print(
            f"Successfully loaded blueprint: '{blueprint_data.get('project_name', 'Unknown Project')}' from '{filepath}'"
        )
        return blueprint_data
    except json.JSONDecodeError as e:
        print(f"Error: Could not parse JSON file '{filepath}'. Invalid JSON: {e}")
        return None
    except Exception as e:
        print(f"An unexpected error occurred while loading '{filepath}': {e}")
        return None


def generate_initial_cpp_stub(blueprint_data):
    """
    Generates a very basic C++ stub based on a few blueprint parameters.
    This is a temporary function for Step 1.B.
    Args:
        blueprint_data (dict): The parsed blueprint data.
    Returns:
        str: A basic C++ code string.
    """
    if not blueprint_data:
        return "// Blueprint data was not loaded. Cannot generate C++ stub."

    project_name = blueprint_data.get("project_name", "Untitled_Project")  # noqa: F841
    target_mode = blueprint_data.get("esp32_target_mode", "NOT_SPECIFIED")  # noqa: F841

    tflm_options = blueprint_data.get("tflm_options", {})
    tflm_enabled_code_val = tflm_options.get("enable_tflm", 0)  # noqa: F841

    main_sensors_cfg = blueprint_data.get("main_sensors_config", {})
    num_main_sensors = main_sensors_cfg.get("number_of_sensors", 0)  # noqa: F841

    # This is a very simple C++ stub for demonstration in this step
    cpp_stub_code = """// ======================================================
// Project: {project_name}
// Generated by Python Configurator App - Step 1.B.3
// ESP32 Target Mode: {target_mode}
// TFLM Enabled (USE_TFLM): {tflm_enabled_code_val}
// ======================================================

#define NUM_MAIN_SENSORS {num_main_sensors}

// --- Further C++ code will be generated in subsequent steps ---

void setup() {{
  Serial.begin(115200);
  Serial.println("ESP32 Sketch Initialized from Python Configurator App!");
  Serial.print("Project Name: ");
  Serial.println("{project_name}");
  Serial.print("Target Mode: ");
  Serial.println("{target_mode}");
  Serial.print("Number of Main Sensors: ");
  Serial.println({num_main_sensors});
}}

void loop() {{
  // Main loop for the ESP32
  delay(2000); // Placeholder delay
}}
"""
    return cpp_stub_code


# This is the main part of the script that runs when you execute it
if __name__ == "__main__":
    print("--- ESP32 Pipeline Configurator App (Step 1.B.3) ---")

    blueprint_file_path = "blueprint.json"  # Name of our configuration file

    # Attempt to load the blueprint data
    current_blueprint = load_blueprint(blueprint_file_path)

    if current_blueprint:
        print("-" * 40)
        print("Blueprint Configuration Summary (from " + blueprint_file_path + "):")
        print(f"  Project Name:       {current_blueprint.get('project_name', 'N/A')}")
        print(
            f"  ESP32 Target Mode:  {current_blueprint.get('esp32_target_mode', 'N/A')}"
        )

        tflm_opt = current_blueprint.get("tflm_options", {})
        print(f"  TFLM Enabled:       {tflm_opt.get('enable_tflm', 'N/A')}")

        pipeline_props = current_blueprint.get("pipeline_properties", {})
        print(f"  Pipeline Length:    {pipeline_props.get('total_length_m', 'N/A')} m")
        print(
            f"  Update Interval:    {pipeline_props.get('update_interval_ms', 'N/A')} ms"
        )

        main_sensors_info = current_blueprint.get("main_sensors_config", {})
        num_s = main_sensors_info.get("number_of_sensors", 0)
        print(f"  Num Main Sensors:   {num_s}")

        if num_s > 0:
            print(
                f"  Use Global K-Factor: {main_sensors_info.get('use_global_k_factor', 'N/A')}"
            )
            if main_sensors_info.get(
                "use_global_k_factor", False
            ):  # Corrected: Check boolean directly
                print(
                    f"    Global K:       {main_sensors_info.get('global_k_factor_pulses_per_liter', 'N/A')}"
                )

            print("  Sensor Specifics:")
            for i, sensor_details in enumerate(main_sensors_info.get("sensors", [])):
                hint = sensor_details.get("id_ui_hint", f"S{i+1}")
                pin = sensor_details.get("gpio_pin", "N/A")
                # For K-factor display, show it if use_global_k_factor is false, OR always show individual from list
                # Simplified: always show individual if present, else show 'Uses Global' if global is true.
                # This needs to match how it will be USED later. For now, just display what's in the sensor object if present.
                k_factor_val = sensor_details.get("k_factor_pulses_per_liter")

                print(f"    {hint}: Pin={pin}", end="")
                if (
                    k_factor_val is not None
                ):  # Check if k_factor_pulses_per_liter exists for this sensor
                    print(f", K-Factor={k_factor_val}", end="")
                elif not main_sensors_info.get(
                    "use_global_k_factor", True
                ):  # If global K is false AND specific is missing, that's odd.
                    print(", K-Factor=MISSING", end="")
                # if use_global_k_factor is true, individual K-factors are ignored, so we don't strictly need to print them then.
                # For summary, if it exists in sensor object, we can show it, acknowledging it may be overridden.
                # A clearer display for K-Factor during this summary part might be:
                # k_to_display = "Uses Global"
                # if not main_sensors_info.get('use_global_k_factor', True): # If NOT using global
                #    k_to_display = sensor_details.get('k_factor_pulses_per_liter', 'MISSING in sensor object')
                # print(f"    {hint}: Pin={pin}, K-Factor Display = {k_to_display}", end="")

                print()  # Newline
        print("-" * 40)

        # Generate the C++ stub
        generated_cpp = generate_initial_cpp_stub(current_blueprint)

        # Create a filename for the output .ino file
        safe_project_name = (
            current_blueprint.get("project_name", "generated_sketch")
            .replace(" ", "_")
            .replace("-", "_")
        )
        output_ino_filename = f"{safe_project_name}_step1B.ino"

        try:
            with open(output_ino_filename, "w") as outfile:
                outfile.write(generated_cpp)
            print(f"\nSuccessfully wrote initial C++ stub to '{output_ino_filename}'")
            print("\nReview the content of this .ino file.")
        except IOError as e:
            print(f"\nError: Could not write to file '{output_ino_filename}': {e}")
        except Exception as e:
            print(f"\nAn unexpected error occurred while writing file: {e}")
    else:
        print(
            f"Failed to load blueprint. Please ensure '{blueprint_file_path}' exists in the same directory and is valid JSON."
        )

    print("--- Script Finished ---")
