// ======================================================
// Project: MyFirstPipelineProject
// Generated by Python Configurator App - Step 1.B.3
// ESP32 Target Mode: REAL_SENSORS
// TFLM Enabled (USE_TFLM): 0
// ======================================================

#define NUM_MAIN_SENSORS 2

// --- Further C++ code will be generated in subsequent steps ---

void setup() {
  Serial.begin(115200);
  Serial.println("ESP32 Sketch Initialized from Python Configurator App!");
  Serial.print("Project Name: ");
  Serial.println("MyFirstPipelineProject");
  Serial.print("Target Mode: ");
  Serial.println("REAL_SENSORS");
  Serial.print("Number of Main Sensors: ");
  Serial.println(2);
}

void loop() {
  // Main loop for the ESP32
  delay(2000); // Placeholder delay
}
