import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import (  # noqa: F401
    LabelEncoder,
    StandardScaler,
)  # StandardScaler optional
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt  # Optional: for visualizing history  # noqa: F401

print(f"Using TensorFlow version: {tf.__version__}")

# --- Configuration ---
# UPDATE: Point to the new CSV file generated by the parameter simulator
INPUT_CSV = "simulated_leak_data_pipeline_params.csv"
MODEL_SAVE_PATH = "leak_detection_model.h5"
TFLITE_SAVE_PATH = "model.tflite"
VALIDATION_SPLIT = 0.2  # Use 20% of training data for validation during training
TEST_SPLIT = 0.15  # Hold back 15% of total data for final testing

# === 1. Load and Prepare Data ===
print(f"Loading data from {INPUT_CSV}...")
df = pd.read_csv(INPUT_CSV)

# Basic check
if df.isnull().sum().sum() > 0:
    print("Warning: Missing values found. Consider imputation or dropping rows.")
    # df = df.dropna() # Example: drop rows with missing values

print("Data loaded. Calculating standard flow features...")

# === 2. Feature Engineering (MUST MATCH ESP32 get_ml_features ORDER!) ===
# Calculate differences (if not already in CSV, these need calculating)
# These likely *are not* in the new CSV, so calculate them:
df["Diff12"] = df["flowRate1"] - df["flowRate2"]
df["Diff23"] = df["flowRate2"] - df["flowRate3"]
df["TotalDif"] = df["flowRate1"] - df["flowRate3"]

# Calculate Rate of Change (requires looking at previous row)
# Sort by timestamp first to be sure (important if data wasn't perfectly sequential)
df = df.sort_values(by="timestamp")
# Calculate change from previous time step. Fill first value with 0.
df["TotalDiff_prev"] = df["TotalDif"].shift(1)
df["DiffChange"] = (df["TotalDif"] - df["TotalDiff_prev"]).fillna(0)

# *** Define YOUR Feature List (ORDER IS CRITICAL!) ***
# UPDATE: Include the pipeline parameters from the CSV as features.
# This list MUST match the order and content of get_ml_features in C++
# and the value used for ML_FEATURE_COUNT
FEATURE_COLUMNS = [
    # Standard Flow Features
    "flowRate1",  # Index 0
    "flowRate2",  # Index 1
    "flowRate3",  # Index 2
    "TotalDif",  # Index 3 (Calculated above)
    "DiffChange",  # Index 4 (Calculated above)
    # Pipeline Parameters (from the CSV)
    "pipelineLength",  # Index 5
    "pipeDiameter",  # Index 6
    "kFactorSum",  # Index 7
]
TARGET_COLUMN = "label"  # Assumes label column is still named 'label'

print(
    f"Using {len(FEATURE_COLUMNS)} features: {FEATURE_COLUMNS}"
)  # Will now print 8 features
X = df[FEATURE_COLUMNS].values
y_labels = df[TARGET_COLUMN].values

# Encode labels (Strings to Integers 0, 1, 2...)
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y_labels)
num_classes = len(
    label_encoder.classes_
)  # Should still be 12 if generator labels are same
print(f"\nFound {num_classes} unique classes:")
# Print the mapping - CRITICAL for setting ML_CLASS_NAMES in ESP32 code
# ** PAY CLOSE ATTENTION TO THIS OUTPUT AND NOTE IT DOWN **
label_mapping = dict(
    zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_))
)
print("CRITICAL LABEL MAPPING (Label -> Integer):")
print(label_mapping)
print("--- Ensure ML_CLASS_NAMES in ESP32 matches this order! ---")

# === 3. Split Data ===
X_train_val, X_test, y_train_val, y_test = train_test_split(
    X, y, test_size=TEST_SPLIT, random_state=42, stratify=y
)
print(f"\nData split: Train+Val={len(X_train_val)}, Test={len(X_test)}")

# === 4. (Optional) Scale Features ===
# Consider scaling, especially since pipeline parameters might have different ranges
# If you enable scaling, you MUST implement inverse scaling or scale on ESP32 too!
# scaler = StandardScaler()
# X_train_val = scaler.fit_transform(X_train_val)
# X_test = scaler.transform(X_test)
# print("Features scaled. Remember to handle scaling during inference!")

# === 5. Build the Keras Model ===
print("\nBuilding Keras model...")
# UPDATE: Consider increasing neuron counts slightly due to more features
model = tf.keras.models.Sequential(
    [
        # Input layer matches new feature count (len(FEATURE_COLUMNS) will be 8)
        tf.keras.layers.InputLayer(input_shape=(len(FEATURE_COLUMNS),)),
        tf.keras.layers.Dense(
            24, activation="relu"
        ),  # Hidden layer 1 (e.g., 24 neurons)
        tf.keras.layers.Dense(
            12, activation="relu"
        ),  # Hidden layer 2 (e.g., 12 neurons)
        # tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Dense(num_classes, activation="softmax"),  # Output layer
    ]
)

model.compile(
    optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"]
)

model.summary()  # Check input shape matches (None, 8)

# === 6. Train the Model ===
print("\nTraining model...")
# UPDATE: Consider slightly more epochs if validation accuracy is still improving
EPOCHS = 60  # Adjust as needed
BATCH_SIZE = 32  # Adjust as needed

history = model.fit(
    X_train_val,
    y_train_val,
    epochs=EPOCHS,
    batch_size=BATCH_SIZE,
    validation_split=VALIDATION_SPLIT,
    callbacks=[
        tf.keras.callbacks.EarlyStopping(
            monitor="val_loss", patience=12, restore_best_weights=True
        )  # Increased patience slightly
    ],
    verbose=2,
)

print("\nTraining complete.")

# === 7. Evaluate the Model ===
print("\nEvaluating model on test data...")
test_loss, test_acc = model.evaluate(X_test, y_test, verbose=0)
print(f"\nTest accuracy: {test_acc*100:.2f}%")
print(f"Test loss: {test_loss:.4f}")

print("\nClassification Report:")
y_pred_probabilities = model.predict(X_test)
y_pred = np.argmax(y_pred_probabilities, axis=1)
# Use target_names from the fitted encoder
print(classification_report(y_test, y_pred, target_names=label_encoder.classes_))

print("\nConfusion Matrix:")
print(
    pd.DataFrame(
        confusion_matrix(y_test, y_pred),
        index=label_encoder.classes_,
        columns=label_encoder.classes_,
    )
)

# === 8. Convert to TensorFlow Lite ===
print(f"\nConverting model to TFLite format ({TFLITE_SAVE_PATH})...")
converter = tf.lite.TFLiteConverter.from_keras_model(model)
# Add optimizations if desired (Optional, test impact on accuracy/size)
# converter.optimizations = [tf.lite.Optimize.DEFAULT]
# ... other optimization options ...

tflite_model = converter.convert()

with open(TFLITE_SAVE_PATH, "wb") as f:
    f.write(tflite_model)
print(
    f"TFLite model saved successfully to {TFLITE_SAVE_PATH} ({len(tflite_model)} bytes)"
)

# === 9. Final Instructions ---
# UPDATE: Reflect the new feature count (8) and emphasize C++ changes
print("\nNEXT STEPS:")
print(
    f"1. Use 'xxd -i {TFLITE_SAVE_PATH} > model_data.cc' in Git Bash to create the C array."
)
print("2. Copy the array content from 'model_data.cc' into your ESP32 code.")
print("3. Update ESP32 Constants:")
print(f"   - Set ML_FEATURE_COUNT to {len(FEATURE_COLUMNS)}.")  # Should be 8
print(f"   - Set ML_OUTPUT_CLASSES to {num_classes}.")  # Should be 12
print(
    "   - Set ML_CLASS_NAMES array using the *exact order* from the 'CRITICAL LABEL MAPPING' printed above."
)
print(
    f"4. Modify the ESP32 'get_ml_features()' function to provide all {len(FEATURE_COLUMNS)} features"
)
print(
    "   in the exact order defined by FEATURE_COLUMNS, including pipeline parameters:"
)
print(f"   {FEATURE_COLUMNS}")
print(
    "5. Ensure ESP32 constants (PIPELINE_LENGTH, etc.) used in get_ml_features are correct for the *current* hardware."
)
print(
    "6. Adjust kTensorArenaSize in ESP32 code if needed (might need more for a slightly larger model)."
)
print("7. Compile, Upload, and Test thoroughly!")

# Optional: Plot training history
# ... (plotting code unchanged) ...
