"""Module docstring."""
import json
import os

import numpy as np
import trimesh

from gaitform.cad.generator import CADGenerator
from gaitform.mapping.rules import OrthoticParams, RigidityZone


def test_noisy_scan_resilience():
    print("--- STARTING NOISY SCAN STRESS TEST ---")

    # 1. Load the original clean STL
    scan_path = os.path.join(os.path.dirname(__file__), "..", "data", "orthotic.stl")
    if not os.path.exists(scan_path):
        print(f"Error: {scan_path} not found.")
        return

    mesh = trimesh.load(scan_path)
    print(f"Loaded clean mesh with {len(mesh.vertices)} vertices.")

    # 2. Add aggressive noise to simulate a bad smartphone scan
    # Randomly displace vertices by up to +/- 5mm
    noise = np.random.uniform(-5.0, 5.0, mesh.vertices.shape)
    mesh.vertices += noise

    noisy_scan_path = os.path.join(
        os.path.dirname(__file__), "..", "data", "noisy_orthotic_temp.stl"
    )
    mesh.export(noisy_scan_path)
    print(f"Created noisy mesh at {noisy_scan_path}.")

    # 3. Load parameters
    params_path = os.path.join(os.path.dirname(__file__), "..", "data", "params.json")
    with open(params_path, "r") as f:
        d = json.load(f)["orthotic_parameters"]["left"]

    params = OrthoticParams(
        arch_height_mm=d["arch_height_mm"],
        heel_cup_depth_mm=d["heel_cup_depth_mm"],
        medial_post_deg=d["medial_post_deg"],
        lateral_post_deg=d["lateral_post_deg"],
        met_pad_position_mm=d["met_pad_position_mm"],
        rigidity_zones=[
            RigidityZone(**z) if isinstance(z, dict) else z for z in d["rigidity_zones"]
        ],
        flags_for_review=[],
    )

    # 4. Run the generator with the noisy scan
    generator = CADGenerator()
    try:
        print("Feeding noisy mesh into CADGenerator raycaster...")
        generated_mesh = generator.generate_mesh(
            params, foot_side="left", shoe_size_mm=273.0, scan_path=noisy_scan_path
        )
        assert generated_mesh is not None
        print("SUCCESS: CADGenerator survived the noisy mesh without crashing!")

        # Check flags
        print("\nFlags generated by engine:")
        for flag in params.flags_for_review:
            print(f"- {flag}")

        if any(
            "exceeds" in flag and "tolerance" in flag
            for flag in params.flags_for_review
        ):
            print(
                "\nVERIFIED: The +/- 1.5mm deviation tolerance flag correctly caught the noisy scan!"
            )
        else:
            print("\nWARNING: The deviation flag did NOT trigger as expected.")

    except RuntimeError as e:
        print(
            f"\nCRITICAL FAILURE: Engine crashed when processing noisy mesh. Exception: {e}"
        )

    finally:
        # Cleanup
        if os.path.exists(noisy_scan_path):
            os.remove(noisy_scan_path)


if __name__ == "__main__":
    test_noisy_scan_resilience()
